language: python
python:
  - "2.7"

# Install dependencies
before_install:
  - sudo apt-get update -qq
  - pip install flake8
  - pip install pep8-naming
  - pip install flake8-commas
install:
  - pip install -r requirements.txt
  - pip install -r tests-requirements.txt
  - pip install .

# Command to run tests
script:
  - flake8
  - python -m pytest tests/ov
  # - python -m pytest tests/server_client # test also require openwsn-fw so for now not working on Travis
